apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: pulsestream
  labels:
    app.kubernetes.io/part-of: pulsestream
    app.kubernetes.io/component: postgres
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
