stages:
  - build
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository

build:
  stage: build
  image: maven:3.9.9-eclipse-temurin-21
  script:
    - cd services/ingestion-service
    - mvn clean compile
  only:
    - merge_requests
    - main
    - dev

test:
  stage: test
  image: maven:3.9.9-eclipse-temurin-21
  script:
    - cd services/ingestion-service
    - mvn test
  only:
    - merge_requests
    - main
    - dev