apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: pulsestream
  labels:
    app.kubernetes.io/part-of: pulsestream
    app.kubernetes.io/component: grafana
data:
  prometheus.yml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        editable: true
        jsonData:
          timeInterval: 15s
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-provider
  namespace: pulsestream
  labels:
    app.kubernetes.io/part-of: pulsestream
    app.kubernetes.io/component: grafana
data:
  dashboards.yml: |
    apiVersion: 1

    providers:
      - name: pulsestream
        orgId: 1
        folder: PulseStream
        type: file
        disableDeletion: false
        updateIntervalSeconds: 30
        allowUiUpdates: true
        options:
          path: /etc/grafana/dashboards
          foldersFromFilesStructure: false
