apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: pulsestream
  labels:
    app.kubernetes.io/part-of: pulsestream
    app.kubernetes.io/component: zookeeper
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/component: zookeeper
  ports:
    - name: client
      port: 2181
      targetPort: 2181
