{
 "title": "Ingestion Metrics",
 "tags": [ "pulsestream" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"ingestion-service\", uri=\"/api/v1/events\"}[1m]))",
     "legendFormat": "requests/s"
    }
   ]
  },
  {
   "title": "Success / Failure Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (outcome) (increase(http_server_requests_seconds_count{job=\"ingestion-service\", uri=\"/api/v1/events\"}[1m]))",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "Latency (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{job=\"ingestion-service\", uri=\"/api/v1/events\"}[1m])) / sum(rate(http_server_requests_seconds_count{job=\"ingestion-service\", uri=\"/api/v1/events\"}[1m]))",
     "legendFormat": "avg latency"
    },
    {
     "expr": "max(http_server_requests_seconds_max{job=\"ingestion-service\", uri=\"/api/v1/events\"})",
     "legendFormat": "max latency"
    }
   ]
  }
 ]
}