[CmdletBinding()]
param(
    [string] $Namespace = "default",
    # Name of the Kafka custom resource. Everything the Strimzi operator
    # generates is prefixed with it, including the bootstrap and per-broker
    # Services, so the derived names below follow from this one value.
    [string] $KafkaClusterName = "pulsestream",
    [int] $ExpectedBrokerCount = 3,
    [int] $BootstrapPort = 9092,
    # Image used for the throwaway client pods that exercise the cluster from
    # outside the broker pods. Kept on the same Strimzi/Kafka version as the
    # cluster so the Kafka CLI always matches the brokers.
    [string] $ClientImage = "quay.io/strimzi/kafka:1.1.0-kafka-4.3.0",
    # Platform services whose Kafka connectivity is confirmed. Each is expected
    # to be deployed from infrastructure/kubernetes/<name>/, which names its
    # ConfigMap <name>-config and labels its pods app.kubernetes.io/name=<name>.
    # query-service is absent on purpose: it is a read API and consumes no
    # broker config.
    [string[]] $ServiceNames = @("ingestion-service", "telemetry-processor"),
    # Consumer group the telemetry-processor listener joins, i.e. the default of
    # pulsestream.kafka.consumer.group-id in its application.yml. Override it
    # together with PULSESTREAM_KAFKA_CONSUMER_GROUP_ID.
    [string] $ProcessorServiceName = "telemetry-processor",
    [string] $ProcessorConsumerGroup = "telemetry-processor",
    [int] $ProbeMessageCount = 10,
    # How long the probe consumer waits for records before it gives up. Generous
    # because the first consumer in a group also pays for the group join.
    [int] $ConsumeTimeoutMs = 30000,
    [int] $TimeoutSeconds = 300
)

$ErrorActionPreference = "Stop"

Import-Module (Join-Path $PSScriptRoot "lib\PulseStreamValidation.psm1") -Force
Import-Module (Join-Path $PSScriptRoot "lib\PulseStreamKubernetes.psm1") -Force

# Service names are generated by the operator, not declared in this repository,
# so they are derived here exactly as Strimzi derives them.
$bootstrapServiceName = "$KafkaClusterName-kafka-bootstrap"
$bootstrapAddress = "$($bootstrapServiceName):$BootstrapPort"
$brokersServiceName = "$KafkaClusterName-kafka-brokers"
# Selects the broker pods only. strimzi.io/cluster is not specific enough: it is
# also carried by the Entity Operator pod the topic work will add (#141), which
# would then be counted as a broker by the checks below.
$brokerPodSelector = "strimzi.io/name=$KafkaClusterName-kafka"
# The Strimzi Kafka image keeps the CLI outside PATH.
$kafkaBinPath = "/opt/kafka/bin"

# Every object this run creates carries the same suffix, so a probe topic or
# client pod left behind by an interrupted run is identifiable and never
# collides with a concurrent run.
$runId = [Guid]::NewGuid().ToString('N').Substring(0, 8)
$probeTopic = "pulsestream.validation.$runId"
$probeGroup = "pulsestream-validation-$runId"
$probeMessages = 1..$ProbeMessageCount | ForEach-Object { "pulsestream-validation-$runId-$_" }
# Replicated across every broker, so a message that is acknowledged has been
# written to all of them: this is what makes the round trip below a statement
# about the cluster rather than about one broker.
$probeReplicationFactor = $ExpectedBrokerCount
$probeMinInsyncReplicas = 2

# The Kafka CLI commands are written as literal here-strings with {{PLACEHOLDER}}
# markers rather than interpolated PowerShell strings, because every `$` in a
# shell snippet would otherwise need escaping and one missed backtick would
# silently produce an empty variable inside the pod.
function New-ShellCommand {
    param(
        [Parameter(Mandatory)] [string] $Template,
        [Parameter(Mandatory)] [hashtable] $Values
    )

    $command = $Template
    foreach ($key in $Values.Keys) {
        $command = $command.Replace("{{$key}}", [string] $Values[$key])
    }

    # Line endings are normalized because these scripts are edited on Windows and
    # .gitattributes pins eol=lf for *.sh only, so a *.ps1 here-string is checked
    # out with CRLF. bash keeps the CR as part of the last token on each line and
    # rejects the command with "syntax error near unexpected token $'do\r'".
    return $command -replace "`r`n", "`n" -replace "`r", "`n"
}

function Invoke-KafkaCli {
    param(
        # Becomes part of the client pod name, so it must be unique per call and
        # DNS-1123 safe.
        [Parameter(Mandatory)] [string] $Purpose,
        [Parameter(Mandatory)] [string] $Command
    )

    Invoke-KafkaClientCommand `
        -Namespace $Namespace `
        -PodName "kafka-validation-$Purpose-$runId" `
        -Image $ClientImage `
        -TimeoutSeconds $TimeoutSeconds `
        -Command $Command
}

Write-Host "Validating Kafka broker health and cluster connectivity..."

# 0. Fail fast with a clear message if there is no reachable cluster, rather
#    than letting every later check fail with a connection error.
Invoke-KubectlChecked `
    -KubectlArgs @("cluster-info") `
    -ErrorContext "kubectl cannot reach a Kubernetes cluster" | Out-Null
$currentContext = (Invoke-KubectlChecked `
    -KubectlArgs @("config", "current-context") `
    -ErrorContext "Could not determine the current kubectl context").Trim()
Write-Host "[ok] Connected to Kubernetes context '$currentContext' (namespace: $Namespace)"

# 1. Acceptance criterion: the brokers report a healthy state. The operator's
#    own verdict comes first -- a Ready Kafka resource means it reconciled the
#    cluster, not merely that pods exist. Retried because this script is also
#    run right after a rollout, where a cold start pulls the Kafka image first.
Invoke-WithRetry `
    -TimeoutSeconds $TimeoutSeconds `
    -FailureMessage "The Kafka resource '$KafkaClusterName' did not become Ready within $TimeoutSeconds seconds." `
    -Operation {
        $readyCondition = Get-KubectlJsonPath `
            -KubectlArgs @("get", "kafka", $KafkaClusterName, "--namespace", $Namespace, "-o", "jsonpath={.status.conditions[?(@.type=='Ready')].status}") `
            -ErrorContext "The Kafka resource '$KafkaClusterName' was not found in namespace '$Namespace'. Deploy infrastructure/kubernetes/kafka/ first"

        Confirm-Condition `
            -Condition ($readyCondition -eq "True") `
            -SuccessMessage "The operator reports Kafka resource '$KafkaClusterName' as Ready" `
            -FailureMessage "Kafka resource '$KafkaClusterName' is not Ready (condition: '$readyCondition')"
    }

$brokerPodNames = @((Get-KubectlJsonPath `
    -KubectlArgs @("get", "pods", "--namespace", $Namespace, "-l", $brokerPodSelector, "-o", "jsonpath={.items[*].metadata.name}") `
    -ErrorContext "Could not list the broker pods") -split "\s+" | Where-Object { $_ })

Confirm-Condition -Permanent `
    -Condition (@($brokerPodNames).Count -eq $ExpectedBrokerCount) `
    -SuccessMessage "Found $ExpectedBrokerCount broker pods ($($brokerPodNames -join ', '))" `
    -FailureMessage "Found $(@($brokerPodNames).Count) broker pod(s) matching '$brokerPodSelector', expected $ExpectedBrokerCount"

# Readiness is gated by the operator on a real Kafka readiness check, so this is
# stronger than "the pods exist".
$podReadyStates = Get-KubectlJsonPath `
    -KubectlArgs @("get", "pods", "--namespace", $Namespace, "-l", $brokerPodSelector, "-o", "jsonpath={.items[*].status.conditions[?(@.type=='Ready')].status}") `
    -ErrorContext "Could not read broker pod readiness"

$readyPodCount = @($podReadyStates -split "\s+" | Where-Object { $_ -eq "True" }).Count
Confirm-Condition -Permanent `
    -Condition ($readyPodCount -eq $ExpectedBrokerCount) `
    -SuccessMessage "All $ExpectedBrokerCount broker pods report Ready" `
    -FailureMessage "Only $readyPodCount of $ExpectedBrokerCount broker pods are Ready"

# 2. Each broker is asked directly, over its own per-broker DNS name from the
#    generated headless Service, rather than through the bootstrap Service. A
#    single bootstrap query is answered by whichever broker the client happened
#    to reach, so one broker that accepts no client connections stays invisible
#    to it. The cluster id is read at the same time: three brokers that formed
#    three separate single-node clusters would each answer happily, and only the
#    differing ids expose it.
$brokerAddresses = $brokerPodNames | ForEach-Object { "$_.$brokersServiceName.$Namespace.svc:$BootstrapPort" }

$perBrokerCommand = New-ShellCommand -Values @{
    BIN       = $kafkaBinPath
    ADDRESSES = ($brokerAddresses | ForEach-Object { "'$_'" }) -join " "
} -Template @'
for address in {{ADDRESSES}}; do
  cluster_id="$({{BIN}}/kafka-cluster.sh cluster-id --bootstrap-server "$address" 2>/dev/null | sed -n 's/^Cluster ID: *//p')"
  if [ -n "$cluster_id" ]; then
    echo "BROKER-OK $address $cluster_id"
  else
    echo "BROKER-FAIL $address"
  fi
done
# The per-broker verdicts above are what the checks read; the loop's own exit
# status would only report the last broker.
exit 0
'@

$perBrokerResult = Invoke-KafkaCli -Purpose "brokers" -Command $perBrokerCommand

Confirm-Condition -Permanent `
    -Condition ($perBrokerResult.ExitCode -eq 0) `
    -SuccessMessage "A client pod queried every broker individually" `
    -FailureMessage "The per-broker client pod did not complete. $($perBrokerResult.Output)"

$unreachableBrokers = [regex]::Matches($perBrokerResult.Output, "(?m)^BROKER-FAIL\s+(\S+)\s*$") |
    ForEach-Object { $_.Groups[1].Value }

Confirm-Condition -Permanent `
    -Condition (@($unreachableBrokers).Count -eq 0) `
    -SuccessMessage "Every broker answers client requests on its own '$brokersServiceName' DNS name" `
    -FailureMessage "$(@($unreachableBrokers).Count) broker(s) did not answer on their own DNS name ($($unreachableBrokers -join ', ')). $($perBrokerResult.Output)"

$reportedClusterIds = [regex]::Matches($perBrokerResult.Output, "(?m)^BROKER-OK\s+(\S+)\s+(\S+)\s*$") |
    ForEach-Object { $_.Groups[2].Value } |
    Sort-Object -Unique

Confirm-Condition -Permanent `
    -Condition (@($reportedClusterIds).Count -eq 1) `
    -SuccessMessage "All $ExpectedBrokerCount brokers report the same cluster id ($($reportedClusterIds -join ', '))" `
    -FailureMessage "The brokers report $(@($reportedClusterIds).Count) distinct cluster id(s) ($($reportedClusterIds -join ', ')), so they are not one cluster"

# 3. Acceptance criterion: a test message flow succeeds. Everything above reads
#    Kubernetes objects or cluster metadata; from here on the checks speak the
#    Kafka protocol as a platform service would, through the same bootstrap
#    address the services are configured with.
#
#    The probe topic is created explicitly because auto.create.topics.enable is
#    false on this cluster, and it is a throwaway rather than one of the
#    platform topics: provisioning those is #141, and this script must not leave
#    a topic behind that the topic work then finds already created with the
#    wrong settings.
try {
    $createResult = Invoke-KafkaCli -Purpose "create" -Command (New-ShellCommand -Values @{
        BIN        = $kafkaBinPath
        BOOTSTRAP  = $bootstrapAddress
        TOPIC      = $probeTopic
        PARTITIONS = $ExpectedBrokerCount
        RF         = $probeReplicationFactor
        MIN_ISR    = $probeMinInsyncReplicas
    } -Template @'
{{BIN}}/kafka-topics.sh --bootstrap-server {{BOOTSTRAP}} --create --topic {{TOPIC}} \
  --partitions {{PARTITIONS}} --replication-factor {{RF}} \
  --config min.insync.replicas={{MIN_ISR}} 2>&1
'@)

    Confirm-Condition -Permanent `
        -Condition ($createResult.ExitCode -eq 0) `
        -SuccessMessage "Created probe topic '$probeTopic' (partitions: $ExpectedBrokerCount, replication factor: $probeReplicationFactor, min.insync.replicas: $probeMinInsyncReplicas)" `
        -FailureMessage "Could not create the probe topic '$probeTopic' through '$bootstrapAddress'. $($createResult.Output)"

    # A topic can be created while replicas are still catching up, so the
    # in-sync replica set is asserted before anything is produced: acks=all with
    # min.insync.replicas=2 would otherwise fail on a shrunken ISR and be
    # reported as a producer problem.
    $describeResult = Invoke-KafkaCli -Purpose "describe" -Command (New-ShellCommand -Values @{
        BIN       = $kafkaBinPath
        BOOTSTRAP = $bootstrapAddress
        TOPIC     = $probeTopic
    } -Template @'
{{BIN}}/kafka-topics.sh --bootstrap-server {{BOOTSTRAP}} --describe --topic {{TOPIC}} 2>&1
'@)

    Confirm-Condition -Permanent `
        -Condition ($describeResult.ExitCode -eq 0) `
        -SuccessMessage "The cluster describes probe topic '$probeTopic'" `
        -FailureMessage "Could not describe the probe topic '$probeTopic'. $($describeResult.Output)"

    $partitionLines = [regex]::Matches(
        $describeResult.Output,
        "Partition:\s*(\d+)\s+Leader:\s*(-?\d+)\s+Replicas:\s*([\d,]+)\s+Isr:\s*([\d,]*)")

    Confirm-Condition -Permanent `
        -Condition (@($partitionLines).Count -eq $ExpectedBrokerCount) `
        -SuccessMessage "Probe topic '$probeTopic' has its $ExpectedBrokerCount partitions" `
        -FailureMessage "Probe topic '$probeTopic' reports $(@($partitionLines).Count) partition(s), expected $ExpectedBrokerCount. $($describeResult.Output)"

    $underReplicatedProbePartitions = @($partitionLines | Where-Object {
        @($_.Groups[4].Value -split "," | Where-Object { $_ }).Count -ne $probeReplicationFactor
    })

    Confirm-Condition -Permanent `
        -Condition (@($underReplicatedProbePartitions).Count -eq 0) `
        -SuccessMessage "Every probe partition has all $probeReplicationFactor replicas in sync" `
        -FailureMessage "$(@($underReplicatedProbePartitions).Count) probe partition(s) have fewer than $probeReplicationFactor in-sync replicas. $($describeResult.Output)"

    # Leaders are reported rather than asserted: replica assignment is the
    # cluster's to make, so an uneven spread is not a fault.
    $partitionLeaders = @($partitionLines | ForEach-Object { $_.Groups[2].Value } | Sort-Object -Unique)
    Write-Host "[ok] Probe partitions are led by $(@($partitionLeaders).Count) broker(s) (ids: $($partitionLeaders -join ', '))"

    # acks=all is the point of this publish: with min.insync.replicas=2 the
    # broker only acknowledges once the record is on a second broker, so a
    # successful produce is evidence of working replication, not just of a
    # reachable leader.
    $produceResult = Invoke-KafkaCli -Purpose "produce" -Command (New-ShellCommand -Values @{
        BIN       = $kafkaBinPath
        BOOTSTRAP = $bootstrapAddress
        TOPIC     = $probeTopic
        PAYLOADS  = ($probeMessages -join "\n") + "\n"
    } -Template @'
printf '{{PAYLOADS}}' | {{BIN}}/kafka-console-producer.sh \
  --bootstrap-server {{BOOTSTRAP}} --topic {{TOPIC}} \
  --producer-property acks=all 2>&1
'@)

    Confirm-Condition -Permanent `
        -Condition ($produceResult.ExitCode -eq 0) `
        -SuccessMessage "Produced $ProbeMessageCount messages to '$probeTopic' with acks=all" `
        -FailureMessage "A producer could not publish to '$probeTopic' through '$bootstrapAddress'. $($produceResult.Output)"

    # Consumed as a group rather than with --from-beginning alone, so the group
    # coordinator and the replicated __consumer_offsets topic are exercised too:
    # a cluster that serves produce and fetch but cannot coordinate groups would
    # break every platform consumer while passing a plain read-back.
    $consumeResult = Invoke-KafkaCli -Purpose "consume" -Command (New-ShellCommand -Values @{
        BIN        = $kafkaBinPath
        BOOTSTRAP  = $bootstrapAddress
        TOPIC      = $probeTopic
        GROUP      = $probeGroup
        COUNT      = $ProbeMessageCount
        TIMEOUT_MS = $ConsumeTimeoutMs
    } -Template @'
{{BIN}}/kafka-console-consumer.sh --bootstrap-server {{BOOTSTRAP}} --topic {{TOPIC}} \
  --group {{GROUP}} --from-beginning --max-messages {{COUNT}} --timeout-ms {{TIMEOUT_MS}} \
  --consumer-property enable.auto.commit=true 2>&1
'@)

    Confirm-Condition -Permanent `
        -Condition ($consumeResult.ExitCode -eq 0) `
        -SuccessMessage "A consumer in group '$probeGroup' read from '$probeTopic'" `
        -FailureMessage "A consumer could not read '$probeTopic' through '$bootstrapAddress' within $ConsumeTimeoutMs ms. $($consumeResult.Output)"

    # Every produced payload must come back, so a partially delivered batch is a
    # failure rather than a pass on the first record.
    $consumedMessages = @($consumeResult.Output -split "\r?\n" | Where-Object { $_ -like "pulsestream-validation-$runId-*" })
    $missingMessages = @($probeMessages | Where-Object { $consumedMessages -notcontains $_ })

    Confirm-Condition -Permanent `
        -Condition (@($missingMessages).Count -eq 0) `
        -SuccessMessage "All $ProbeMessageCount produced messages were consumed unchanged" `
        -FailureMessage "$(@($missingMessages).Count) of $ProbeMessageCount produced messages were not consumed (first missing: $($missingMessages | Select-Object -First 1)). $($consumeResult.Output)"

    # The consumer committed on close, so its offsets are readable now. Summing
    # them proves the commits reached the offsets topic; the lag column proves
    # nothing was left behind.
    $groupResult = Invoke-KafkaCli -Purpose "offsets" -Command (New-ShellCommand -Values @{
        BIN       = $kafkaBinPath
        BOOTSTRAP = $bootstrapAddress
        GROUP     = $probeGroup
    } -Template @'
{{BIN}}/kafka-consumer-groups.sh --bootstrap-server {{BOOTSTRAP}} --describe --group {{GROUP}} 2>&1
'@)

    Confirm-Condition -Permanent `
        -Condition ($groupResult.ExitCode -eq 0) `
        -SuccessMessage "The cluster describes consumer group '$probeGroup'" `
        -FailureMessage "Could not describe consumer group '$probeGroup'. $($groupResult.Output)"

    # Columns are GROUP TOPIC PARTITION CURRENT-OFFSET LOG-END-OFFSET LAG ...
    # A partition the group committed nothing for prints "-", which is read as
    # zero here: the totals below are what the assertions are about.
    $offsetRows = @($groupResult.Output -split "\r?\n" |
        Where-Object { $_ -match "^\s*$([regex]::Escape($probeGroup))\s+$([regex]::Escape($probeTopic))\s" } |
        ForEach-Object { , (($_ -split "\s+") | Where-Object { $_ }) })

    $toOffset = { param($value) if ($value -match "^\d+$") { [long] $value } else { 0 } }
    $committedTotal = ($offsetRows | ForEach-Object { & $toOffset $_[3] } | Measure-Object -Sum).Sum
    if ($null -eq $committedTotal) { $committedTotal = 0 }
    $laggingPartitions = @($offsetRows | Where-Object { (& $toOffset $_[5]) -gt 0 })

    Confirm-Condition -Permanent `
        -Condition ($committedTotal -eq $ProbeMessageCount) `
        -SuccessMessage "Group '$probeGroup' committed offsets for all $ProbeMessageCount messages" `
        -FailureMessage "Group '$probeGroup' committed offsets totalling $committedTotal, expected $ProbeMessageCount. $($groupResult.Output)"

    Confirm-Condition -Permanent `
        -Condition (@($laggingPartitions).Count -eq 0) `
        -SuccessMessage "Group '$probeGroup' has no lag left on '$probeTopic'" `
        -FailureMessage "Group '$probeGroup' still reports lag on $(@($laggingPartitions).Count) partition(s). $($groupResult.Output)"

    # Asked cluster-wide and only now that real records exist: an internal topic
    # (__consumer_offsets, created by the group above) or a platform topic that
    # lost replicas is a broker health problem even though every check so far
    # passed on the probe topic.
    $replicationResult = Invoke-KafkaCli -Purpose "replication" -Command (New-ShellCommand -Values @{
        BIN       = $kafkaBinPath
        BOOTSTRAP = $bootstrapAddress
    } -Template @'
echo "===UNDER-REPLICATED==="
{{BIN}}/kafka-topics.sh --bootstrap-server {{BOOTSTRAP}} --describe --under-replicated-partitions 2>&1
echo "===UNAVAILABLE==="
{{BIN}}/kafka-topics.sh --bootstrap-server {{BOOTSTRAP}} --describe --unavailable-partitions 2>&1
'@)

    Confirm-Condition -Permanent `
        -Condition ($replicationResult.ExitCode -eq 0) `
        -SuccessMessage "Queried the cluster for under-replicated and unavailable partitions" `
        -FailureMessage "Could not query partition health through '$bootstrapAddress'. $($replicationResult.Output)"

    $underReplicatedSection = [regex]::Match($replicationResult.Output, "(?s)===UNDER-REPLICATED===(.*?)===UNAVAILABLE===").Groups[1].Value
    $unavailableSection = [regex]::Match($replicationResult.Output, "(?s)===UNAVAILABLE===(.*)$").Groups[1].Value

    Confirm-Condition -Permanent `
        -Condition ([string]::IsNullOrWhiteSpace($underReplicatedSection)) `
        -SuccessMessage "No under-replicated partitions anywhere in the cluster" `
        -FailureMessage "The cluster reports under-replicated partitions.$([Environment]::NewLine)$($underReplicatedSection.Trim())"

    Confirm-Condition -Permanent `
        -Condition ([string]::IsNullOrWhiteSpace($unavailableSection)) `
        -SuccessMessage "No unavailable partitions anywhere in the cluster" `
        -FailureMessage "The cluster reports unavailable partitions (partitions with no leader).$([Environment]::NewLine)$($unavailableSection.Trim())"
} finally {
    # Runs on failure too, so a failed run does not leave a probe topic and a
    # consumer group behind. Each object is deleted only if it exists, because
    # this block also runs when the failure was the creation itself, and a
    # "topic does not exist" error would then be reported as a cleanup problem.
    # Real cleanup problems are warnings: throwing here would replace the
    # failure that actually matters with a teardown error.
    $cleanupResult = Invoke-KafkaCli -Purpose "cleanup" -Command (New-ShellCommand -Values @{
        BIN       = $kafkaBinPath
        BOOTSTRAP = $bootstrapAddress
        TOPIC     = $probeTopic
        GROUP     = $probeGroup
    } -Template @'
if {{BIN}}/kafka-topics.sh --bootstrap-server {{BOOTSTRAP}} --list 2>/dev/null | grep -qx '{{TOPIC}}'; then
  {{BIN}}/kafka-topics.sh --bootstrap-server {{BOOTSTRAP}} --delete --topic {{TOPIC}} 2>&1 \
    || echo "CLEANUP-FAIL topic {{TOPIC}}"
fi
if {{BIN}}/kafka-consumer-groups.sh --bootstrap-server {{BOOTSTRAP}} --list 2>/dev/null | grep -qx '{{GROUP}}'; then
  {{BIN}}/kafka-consumer-groups.sh --bootstrap-server {{BOOTSTRAP}} --delete --group {{GROUP}} 2>&1 \
    || echo "CLEANUP-FAIL group {{GROUP}}"
fi
# The markers above carry the verdict, so a failed delete does not abort the
# second one.
exit 0
'@)

    if ($cleanupResult.ExitCode -eq 0 -and $cleanupResult.Output -notmatch "CLEANUP-FAIL") {
        Write-Host "[ok] Probe topic '$probeTopic' and consumer group '$probeGroup' are gone from the cluster"
    } else {
        Write-Warning "Could not remove probe topic '$probeTopic' or consumer group '$probeGroup'; delete them manually. $($cleanupResult.Output)"
    }
}

# 4. Acceptance criterion: service connectivity is confirmed. The platform
#    services must already be deployed for this section; the failure messages
#    name that prerequisite rather than reporting a missing object.
foreach ($serviceName in $ServiceNames) {
    $deploymentAvailable = Get-KubectlJsonPath `
        -KubectlArgs @("get", "deployment", $serviceName, "--namespace", $Namespace, "-o", "jsonpath={.status.conditions[?(@.type=='Available')].status}") `
        -ErrorContext "Deployment '$serviceName' was not found in namespace '$Namespace'. Deploy infrastructure/kubernetes/$serviceName/ first"

    Confirm-Condition -Permanent `
        -Condition ($deploymentAvailable -eq "True") `
        -SuccessMessage "Deployment '$serviceName' is Available" `
        -FailureMessage "Deployment '$serviceName' is not Available (condition: '$deploymentAvailable')"

    # Names and readiness are read as two parallel lists rather than as one
    # `{range}` template: a jsonpath template needs embedded double quotes, and
    # Windows PowerShell 5.1 strips them on the way to kubectl, which then
    # rejects the expression ("unrecognized character in action: U+003D '='").
    # The single-quoted filter below survives that, and both queries iterate the
    # same `.items`, so the lists stay index-aligned.
    $servicePodNames = @((Get-KubectlJsonPath `
        -KubectlArgs @("get", "pods", "--namespace", $Namespace, "-l", "app.kubernetes.io/name=$serviceName", "-o", "jsonpath={.items[*].metadata.name}") `
        -ErrorContext "Could not list the pods of '$serviceName'") -split "\s+" | Where-Object { $_ })

    $servicePodReadyStates = @((Get-KubectlJsonPath `
        -KubectlArgs @("get", "pods", "--namespace", $Namespace, "-l", "app.kubernetes.io/name=$serviceName", "-o", "jsonpath={.items[*].status.conditions[?(@.type=='Ready')].status}") `
        -ErrorContext "Could not read the pod readiness of '$serviceName'") -split "\s+" | Where-Object { $_ })

    # Alignment is asserted rather than assumed: a pod that has not been
    # scheduled yet carries no Ready condition, which would shift the readiness
    # list and could pick the wrong pod name.
    Confirm-Condition -Permanent `
        -Condition (@($servicePodNames).Count -eq @($servicePodReadyStates).Count) `
        -SuccessMessage "'$serviceName' has $(@($servicePodNames).Count) pod(s) reporting a Ready condition" `
        -FailureMessage "'$serviceName' has $(@($servicePodNames).Count) pod(s) but $(@($servicePodReadyStates).Count) Ready condition(s); at least one pod is not scheduled yet"

    $readyServicePodIndex = [array]::IndexOf($servicePodReadyStates, "True")
    $readyServicePod = if ($readyServicePodIndex -ge 0) { $servicePodNames[$readyServicePodIndex] } else { $null }

    Confirm-Condition -Permanent `
        -Condition (-not [string]::IsNullOrWhiteSpace($readyServicePod)) `
        -SuccessMessage "'$serviceName' has a Ready pod ($readyServicePod)" `
        -FailureMessage "'$serviceName' has no Ready pod (pods: $($servicePodNames -join ', '); readiness: $($servicePodReadyStates -join ', '))"

    # Read the variable out of the running container, not out of the ConfigMap.
    # The pods take it through envFrom, which is resolved once at pod creation:
    # a ConfigMap edited after the last rollout is already correct in the API
    # server while every running pod still holds the previous value, so the
    # ConfigMap proves nothing about the process that is actually connecting.
    # This reads what the JVM was handed. validate-kafka-kubernetes.ps1 asserts
    # the committed manifests separately.
    # printenv rather than a shell snippet: Windows PowerShell 5.1 mangles the
    # double quotes a `bash -c` one-liner would need (see the base64 note in
    # PulseStreamKubernetes.psm1). printenv also exits non-zero precisely when
    # the variable is unset, which is the distinction this check is about.
    $envProbe = Invoke-Kubectl -KubectlArgs @(
        "exec", $readyServicePod, "--namespace", $Namespace, "--",
        "printenv", "PULSESTREAM_KAFKA_BOOTSTRAP_SERVERS"
    )

    $podBootstrap = $envProbe.Output.Trim()

    # An unset variable is called out separately from a wrong one: it means the
    # Deployment lost its envFrom reference, which reads very differently from a
    # pod that is merely running with a stale value.
    Confirm-Condition -Permanent `
        -Condition ($envProbe.ExitCode -eq 0 -and -not [string]::IsNullOrWhiteSpace($podBootstrap)) `
        -SuccessMessage "Read PULSESTREAM_KAFKA_BOOTSTRAP_SERVERS from pod '$readyServicePod'" `
        -FailureMessage "PULSESTREAM_KAFKA_BOOTSTRAP_SERVERS is unset in pod '$readyServicePod', so '$serviceName' was never given a broker address. $($envProbe.Output)"

    Confirm-Condition -Permanent `
        -Condition ($podBootstrap -eq $bootstrapAddress) `
        -SuccessMessage "Pod '$readyServicePod' runs with the generated bootstrap Service ($podBootstrap)" `
        -FailureMessage "Pod '$readyServicePod' of '$serviceName' runs with PULSESTREAM_KAFKA_BOOTSTRAP_SERVERS='$podBootstrap', but the operator generated '$bootstrapAddress'. If ConfigMap '$serviceName-config' already carries the right value, the pod predates it: roll the Deployment out (kubectl rollout restart deployment/$serviceName --namespace $Namespace)"

    # The connectivity check runs inside the service pod, against the value that
    # pod is actually running with. That is what distinguishes it from the
    # client-pod checks above: it exercises the service's own DNS resolution and
    # network path to the brokers, so a NetworkPolicy or a namespace mismatch
    # that only affects this service is caught here.
    #
    # A TCP connect is the assertion rather than a Kafka client call because the
    # service images carry a JRE and a shell, not the Kafka CLI. bash is present
    # in the eclipse-temurin:17-jre-jammy base image both services build on.
    $bootstrapHost = ($podBootstrap -split ",")[0].Split(":")[0]
    $bootstrapHostPort = ($podBootstrap -split ",")[0].Split(":")[1]

    $tcpProbe = Invoke-Kubectl -KubectlArgs @(
        "exec", $readyServicePod, "--namespace", $Namespace, "--",
        "bash", "-c", "exec 3<>/dev/tcp/$bootstrapHost/$bootstrapHostPort && echo BOOTSTRAP-REACHABLE"
    )

    Confirm-Condition -Permanent `
        -Condition ($tcpProbe.ExitCode -eq 0 -and $tcpProbe.Output -match "BOOTSTRAP-REACHABLE") `
        -SuccessMessage "'$serviceName' reaches '$podBootstrap' from its own pod" `
        -FailureMessage "'$serviceName' cannot reach '$podBootstrap' from pod '$readyServicePod'. $($tcpProbe.Output)"
}

# 5. One platform service is checked at the Kafka protocol level rather than at
#    the network level: telemetry-processor starts its listener at boot, so a
#    running pod holds a live session with the group coordinator. That is proof
#    of a real client session by a service, not just of an open port.
#
#    ingestion-service gets no equivalent assertion on purpose. Its producer is
#    created on the first publish (DefaultKafkaProducerFactory is lazy), so a
#    healthy, idle pod holds no broker connection to observe, and driving it
#    with a real request would need the platform topics that #141 provisions.
#
#    Membership is asserted, not existence. A consumer group outlives the
#    consumers that created it: it stays listed in Empty state with zero members
#    for offsets.retention.minutes (7 days by default) after the last member
#    left. A `--list` containing the group would therefore still pass against a
#    processor that crashed on boot, or against nothing but the residue of an
#    earlier run. `--state` and `--members` are what distinguish a group record
#    from a live client session.
if ($ServiceNames -contains $ProcessorServiceName) {
    # Retried: a pod that is Ready has passed its health probes, but the Kafka
    # listener joins the group on its own schedule, and a group that is mid
    # rebalance reports a transient state for a few seconds. Each attempt runs
    # in its own client pod, so the attempt number is part of the pod name --
    # pods are deleted with --wait=false and the name would otherwise still be
    # taken on the next try.
    # Script-scoped: the retry body runs as a scriptblock invoked from the
    # validation module, so a plain assignment would write a fresh local copy on
    # every attempt and every client pod would be named "...-1".
    $script:membershipAttempt = 0

    Invoke-WithRetry `
        -TimeoutSeconds $TimeoutSeconds `
        -FailureMessage "Consumer group '$ProcessorConsumerGroup' had no active member within $TimeoutSeconds seconds, so '$ProcessorServiceName' has not joined Kafka." `
        -Operation {
            $script:membershipAttempt++

            $groupResult = Invoke-KafkaCli -Purpose "members-$($script:membershipAttempt)" -Command (New-ShellCommand -Values @{
                BIN       = $kafkaBinPath
                BOOTSTRAP = $bootstrapAddress
                GROUP     = $ProcessorConsumerGroup
            } -Template @'
echo "===STATE==="
{{BIN}}/kafka-consumer-groups.sh --bootstrap-server {{BOOTSTRAP}} --describe --group {{GROUP}} --state 2>&1
echo "===MEMBERS==="
{{BIN}}/kafka-consumer-groups.sh --bootstrap-server {{BOOTSTRAP}} --describe --group {{GROUP}} --members 2>&1
'@)

            Confirm-Condition `
                -Condition ($groupResult.ExitCode -eq 0) `
                -SuccessMessage "Described consumer group '$ProcessorConsumerGroup'" `
                -FailureMessage "Could not describe consumer group '$ProcessorConsumerGroup' through '$bootstrapAddress'. $($groupResult.Output)"

            $stateSection = [regex]::Match($groupResult.Output, "(?s)===STATE===(.*?)===MEMBERS===").Groups[1].Value
            $membersSection = [regex]::Match($groupResult.Output, "(?s)===MEMBERS===(.*)$").Groups[1].Value

            # An unknown group is reported by the CLI as a message rather than a
            # non-zero exit, so it is matched explicitly instead of being left to
            # fall through as an unparsable state row.
            Confirm-Condition `
                -Condition ($groupResult.Output -notmatch "does not exist") `
                -SuccessMessage "The cluster knows consumer group '$ProcessorConsumerGroup'" `
                -FailureMessage "Consumer group '$ProcessorConsumerGroup' does not exist on the cluster, so '$ProcessorServiceName' has never connected to Kafka. $($groupResult.Output)"

            # Columns are GROUP COORDINATOR (ID) ASSIGNMENT-STRATEGY STATE #MEMBERS.
            # Parsed from the right because COORDINATOR itself contains a space
            # and ASSIGNMENT-STRATEGY is blank while a group has no members.
            $stateRow = @($stateSection -split "\r?\n" |
                Where-Object { $_ -match "^\s*$([regex]::Escape($ProcessorConsumerGroup))\s" } |
                Select-Object -First 1)

            Confirm-Condition `
                -Condition (@($stateRow).Count -eq 1) `
                -SuccessMessage "Read the state of consumer group '$ProcessorConsumerGroup'" `
                -FailureMessage "Could not read a state row for consumer group '$ProcessorConsumerGroup'. $($groupResult.Output)"

            $stateFields = @($stateRow[0] -split "\s+" | Where-Object { $_ })
            $groupState = $stateFields[-2]
            $reportedMemberCount = $stateFields[-1]

            # Stable is the only state in which the assignment is settled and the
            # processor is consuming. PreparingRebalance and CompletingRebalance
            # are transient and Empty means every member has left, so all three
            # are retried rather than failed permanently.
            Confirm-Condition `
                -Condition ($groupState -eq "Stable") `
                -SuccessMessage "Consumer group '$ProcessorConsumerGroup' is Stable" `
                -FailureMessage "Consumer group '$ProcessorConsumerGroup' is in state '$groupState' with $reportedMemberCount member(s), not Stable"

            Confirm-Condition `
                -Condition ($reportedMemberCount -match "^\d+$" -and [int] $reportedMemberCount -ge 1) `
                -SuccessMessage "Consumer group '$ProcessorConsumerGroup' reports $reportedMemberCount active member(s)" `
                -FailureMessage "Consumer group '$ProcessorConsumerGroup' reports '$reportedMemberCount' members, so no client is currently joined"

            # The member rows are checked as well as the count: they are what
            # ties the membership to a live consumer, carrying the client id and
            # the pod IP of the process currently holding the session.
            # Columns are GROUP CONSUMER-ID HOST CLIENT-ID #PARTITIONS.
            $memberRows = @($membersSection -split "\r?\n" |
                Where-Object { $_ -match "^\s*$([regex]::Escape($ProcessorConsumerGroup))\s" } |
                ForEach-Object { , (($_ -split "\s+") | Where-Object { $_ }) })

            Confirm-Condition `
                -Condition (@($memberRows).Count -ge 1) `
                -SuccessMessage "Consumer group '$ProcessorConsumerGroup' has $(@($memberRows).Count) member row(s)" `
                -FailureMessage "Consumer group '$ProcessorConsumerGroup' listed no members. $($groupResult.Output)"

            # Reported, not asserted: a member that subscribed to a topic which
            # does not exist yet is Stable with zero partitions, and the platform
            # topics are provisioned by #141. Asserting an assignment here would
            # make this script fail for a reason that is not broker health.
            $assignedPartitionTotal = ($memberRows |
                ForEach-Object { if ($_[-1] -match "^\d+$") { [int] $_[-1] } else { 0 } } |
                Measure-Object -Sum).Sum
            if ($null -eq $assignedPartitionTotal) { $assignedPartitionTotal = 0 }

            $memberClients = @($memberRows | ForEach-Object { $_[3] })
            $memberHosts = @($memberRows | ForEach-Object { $_[2] })
            Write-Host "[ok] '$ProcessorServiceName' is an active member of consumer group '$ProcessorConsumerGroup' (client ids: $($memberClients -join ', '); hosts: $($memberHosts -join ', '); partitions assigned: $assignedPartitionTotal)"
        }
}

Write-Host "[ok] Kafka broker health and connectivity validation completed."
